name: Deploy Model and Test API

on:
  push:
    branches:
      - main

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # Step 3: Install dependencies (assuming requirements.txt is in the root folder)
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Ensure this path is correct

      # Step 4: Start the server in the background (example with FastAPI)
      - name: Start the server
        run: |
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &

      # Step 5: Wait for the server to be available
      - name: Wait for the server to be available
        run: |
          sleep 10  # Adjust this based on how long your server takes to start

      # Step 6: Run the curl request
      - name: Test the API
        run: |
          curl -X POST "http://127.0.0.1:8000/chat/" -H "Content-Type: application/json" -d '{"message": "Hello, how are you?"}'
